//Constants APPWRITE
const String APPWRITE_PROJECT_ID = "APPWRITE_PROJECT_ID";
const String APPWRITE_DATABASE_ID = "APPWRITE_DATABASE_ID";
const String APPWRITE_URL = "https://cloud.appwrite.io/v1";

//Collections
const String COLLECTION_PRODUCTS_ID = "COLLECTION_PRODUCTS_ID";
const String COLLECTION_STORAGES_ID = "COLLECTION_STORAGES_ID";

//Constants OPENAI
const String OPENAI_API_KEY = "OPENAI_API_KEY";
